### ISSUE TITLE
Want to use in python project

### ISSUE THREAD

**Issue by kilinchange** [ernestojimenezruiz/logmap-matcher#21]
Dears,
I want to integrate  LogMap in my python project, could you give me some suggestions:

How can I integrate it conveniently, or I can only rewrite LogMap in python by myself ? I would be grateful if there is a logmap-python available.

Thanks a lot & Best Regards,
KilinChange

**Comment by kilinchange** [comment]
It really helps! Thank you for your kind!

**Comment by ernestojimenezruiz** [comment]
We are also working on using alignment systems as a service see: [https://github.com/rupson/knowledge-graph-alignment-as-a-service](https://github.com/rupson/knowledge-graph-alignment-as-a-service)
