### ISSUE TITLE
Adding google translate

### ISSUE THREAD

**Issue by RasmusKlinkJoerg** [ernestojimenezruiz/logmap-matcher#35]
On windows when adding google translate with Maven, you need quotes around "com.googlecode" and "0.97".

So you have:
 mvn install:install-file -Dfile=/home/ernesto/git/logmap3-matcher/lib/google-api-translate-java-0.97.jar -DgroupId="com.googlecode" -DartifactId=google-api-translate-java -Dversion="0.97" -Dpackaging=jar

**Comment by ernestojimenezruiz** [comment]
Many thanks! I have added this to the instructions!

Ernesto
