### ISSUE TITLE
Mvn package failure

### ISSUE THREAD

**Issue by amrapalijz** [ernestojimenezruiz/logmap-matcher#8]
I downloaded logmap-matcher from sourceforge and since the readme file said:
"Development requires a clone of this git repository. You can use the pre-configured Eclipse (Maven) project (dependencies are automatically downloaded).  To generate a JAR file for LogMap from the command line using Maven, run: `mvn package`". I ran mvn package but it gives the error:

[MVNVM] Using maven: 3.2.5
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for logmap-matcher:logmap-matcher:jar:3.0.0-SNAPSHOT
[WARNING] 'dependencies.dependency.systemPath' for com.googlecode:google-api-translate-java:jar should not point at files within the project directory, ${basedir}/lib/google-api-translate-java-0.97.jar will be unresolvable by dependent projects @ line 102, column 17
[WARNING] 'dependencies.dependency.systemPath' for eu.sealsproject.omt:omt-client:jar should not point at files within the project directory, ${basedir}/lib/seals-omt-client.jar will be unresolvable by dependent projects @ line 109, column 17
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building LogMap 3.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ logmap-matcher ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Amrapali/AAStanford/Projects/SIO-Bio2RDF/logmap-matcher/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ logmap-matcher ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 156 source files to /Amrapali/AAStanford/Projects/SIO-Bio2RDF/logmap-matcher/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Amrapali/AAStanford/Projects/SIO-Bio2RDF/logmap-matcher/src/main/java/uk/ac/ox/krr/logmap2/indexing/LightTarjan.java:[17,58] diamond operator is not supported in -source 1.5
  (use -source 7 or higher to enable diamond operator)
[ERROR] /Amrapali/AAStanford/Projects/SIO-Bio2RDF/logmap-matcher/src/main/java/uk/ac/ox/krr/logmap2/indexing/JointIndexManager.java:[403,64] diamond operator is not supported in -source 1.5
  (use -source 7 or higher to enable diamond operator)
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.978 s
[INFO] Finished at: 2016-06-28T21:29:29-07:00
[INFO] Final Memory: 9M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project logmap-matcher: Compilation failure: Compilation failure:
[ERROR] /Amrapali/AAStanford/Projects/SIO-Bio2RDF/logmap-matcher/src/main/java/uk/ac/ox/krr/logmap2/indexing/LightTarjan.java:[17,58] diamond operator is not supported in -source 1.5
[ERROR](use -source 7 or higher to enable diamond operator)
[ERROR] /Amrapali/AAStanford/Projects/SIO-Bio2RDF/logmap-matcher/src/main/java/uk/ac/ox/krr/logmap2/indexing/JointIndexManager.java:[403,64] diamond operator is not supported in -source 1.5
[ERROR](use -source 7 or higher to enable diamond operator)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by vefthym** [comment]
I had the same problem. Open the project in eclipse and change the JRE System Library to 1.7

**Comment by Tomsanm** [comment]
you should google  download google-api-translate-java-0.97 manually, and than install google-api-translate-java-0.97 .

**Comment by tremendows** [comment]
The library "google-api-translate-java" is not up-to-date at the pom.xml or has a bug. 
You have to update the pom.xml this way:
    <dependency>
      <groupId>com.google.api</groupId>
      <artifactId>google-api-translate-java</artifactId>
      <version>0.97</version>
    </dependency>

Source: https://mvnrepository.com/artifact/com.google.api/google-api-translate-java/0.97

**Comment by ernestojimenezruiz** [comment]
For  some reason I was not getting notifications.

The required dependencies not in maven shoudl be installed manually. 

See readme in "lib" folder:

Google API translate for Java version 0.97 is not available in maven. So it has to be manually added to the local repository.

Installing a library in the local maven repository:
mvn install:install-file -Dfile=<path-to-file> -DgroupId=<group-id> -DartifactId=<artifact-id> -Dversion=<version> -Dpackaging=<packaging>

Select group id, artifact id and version as it appears in LogMap's pom file:
<dependency>
    <groupId>com.googlecode</groupId>
    <artifactId>google-api-translate-java</artifactId>
    <version>0.97</version>
</dependency>

e.g.:
mvn install:install-file -Dfile=/home/ernesto/git/logmap3-matcher/lib/google-api-translate-java-0.97.jar -DgroupId=com.googlecode -DartifactId=google-api-translate-java -Dversion=0.97 -Dpackaging=jar

Ernesto
