### ISSUE TITLE
Can't send the matching request via web interface

### ISSUE THREAD

**Issue by gsp2014** [ernestojimenezruiz/logmap-matcher#9]
I try to run LogMap via the web interface: http://krrwebtools.cs.ox.ac.uk/logmap/. I successfully upload 2 ontologies in the form of head entity, relation and tail entity seperated by "\t" in every line. But I can't send the matching request and the button is still greyed out.

**Comment by ernestojimenezruiz** [comment]
For some reason I was not getting notifications of the issues. 

All the required fields should be filled. The input ontologies shoudl be in format accepted by the OWL API. 

Ernesto
